#!/usr/bin/env bash
set -ex

export CO_LOG_LEVEL="DEBUG"

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u gen_sim_reads.py "$@"
